import Link from "next/link"
import Image from "next/image"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
      <style>
          @import url('https://fonts.googleapis.com/css2?family=Rubik&display=swap');
      </style>
        <title>Kefi Cafe</title>
        <script src="https://cdn.tailwindcss.com"></script>
      </head>
      <body style={{fontFamily:"'Rubik', sans-serif"}}>
        <nav class="text-gray-600 body-font">
          <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
            <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
              <span class="ml-3 text-xl">
                <Image src="/kefi.png" width={50} height={50}></Image>
              </span>
            </a>
            <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
              <Link class="mr-5 hover:text-gray-900" href="/dashboard">Home Page</Link>
              <Link class="mr-5 hover:text-gray-900" href="/menu">Menu</Link>
              <Link class="mr-5 hover:text-gray-900" href="/promo">Promo</Link>
              <Link class="mr-5 hover:text-gray-900" href="/contact">Contact</Link>
            </nav>
            <Link href="/autentikasi">
              <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
                Akun
              </button>
            </Link>
          </div>
        </nav>
        <div>
          {children}  
        </div>
        <footer>
        <div class="text-gray-600 body-font" style={{backgroundColor:"#F6ECD1"}}>
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-5">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">We Are Waiting to Serve You!</h1>
      <h2 class="text-xl text-brown-300 tracking-widest font-medium title-font mb-5">KEFI CAFE</h2>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Or Call +62 821 6809 5251</p>
    </div>
    <div class="text-gray-600 body-font">
            <div class="container px-5 py-24 mx-auto">
              <div class="flex flex-wrap -m-4">
                <div class="p-4 lg:w-1/3">
                  <div class="h-full text-center relative">
                    <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">LOCATION</h2>
                    <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">KOMPLEK, Jl. Classic II Jl. Abdul Hakim, Tj. Sari, Kec. Medan Selayang, Kota Medan, Sumatera Utara 20131</h1>
                    <p class="leading-relaxed mb-3">Connect with Us</p>
                    <div class="text-center mt-2 leading-none flex justify-center absolute bottom-0 left-0 w-full py-4">
                      <span class="text-gray-400 mr-3 inline-flex items-center leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                        <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                          <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                          <circle cx="12" cy="12" r="3"></circle>
                        </svg>1.2K
                      </span>
                      <span class="text-gray-400 inline-flex items-center leading-none text-sm">
                        <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                          <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                        </svg>6
                      </span>
                    </div>
                  </div>
                </div>
                <div class="p-4 lg:w-1/3">
                  <div class="h-full">
                    <div class="flex justify-center">
                        <img class="object-cover object-center rounded h-64" alt="hero" src="/background.png" />
                    </div>
                  </div>
                </div>
                <div class="p-4 lg:w-1/3">
                  <div class="h-full text-center relative">
                    <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">Hours</h2>
                    <h1 class="title-font sm:text-2xl text-xl font-medium text-gray-900 mb-3">Open at 09.00 AM - 11.00 PM</h1>
                  </div>
                </div>
              </div>
            </div>
          </div>
  </div>
</div>


<div style={{backgroundColor:"#AA8F63"}}>
    <div class="container px-5 py-6 mx-auto flex items-center sm:flex-row flex-col">
      <a class="flex title-font font-medium items-center md:justify-start justify-center text-white-900">
        <img src="/kefi.png" width={60} height={60}></img>
      </a>
      <p class="text-sm text-white-500 sm:ml-6 sm:mt-0 mt-4">© Intership Del 2023 —
        <a href="kefi.cafeandspace" rel="noopener noreferrer" class="text-white-600 ml-1" target="_blank">@keficafe</a>
      </p>
      <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
        <a class="text-white-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-white-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-white-500">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
          </svg>
        </a>
        <a class="ml-3 text-white-500">
          <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
          </svg>
        </a>
      </span>
    </div>
    </div>

        </footer>
      </body>
    </html>
  )
}
